kind: Service
apiVersion: v1
metadata:
  name: kubernetes-101-service
spec:
  selector:
    app: kubernetes-101-service
  ports :
  - port: 80
    nodePort: 30006
    targetPort: 8080
  type: NodePort 
